### ISSUE TITLE
Journaling@2021-April

### ISSUE THREAD

**Issue by taijusanagi** [taijusanagi/taijusanagi.com#6]
### 20210416
- I started managing blog in Github
- I felt this is very nice way to manage blog
- I want to make issue based blogging more famous

**Comment by taijusanagi** [comment]
### 20210417
- [ ] 20 minutes exercise
- [ ] 20 minutes language

### To-Do 
- [ ] Finish developing Chocoserver
- [ ] Start developing Chocoshop

**Comment by taijusanagi** [comment]
### 20210417
- [x] 20 minutes exercise
- [ ] 20 minutes language
- [ ] 20 minutes reading

### Tracking
- sleep: 5:00-10:00
- weight: 65.4 kg
- fat: 22.9 %

### To-Do 
- [ ] Finish developing Chocoserver
- [ ] Start developing Chocoshop

### Free

**Comment by taijusanagi** [comment]
### 20210417

### Tracking
- sleep: 5:00-11:00
- weight: 64.6 kg
- fat: 21.4 %

### Routine
- [x] open journal
- [x] task organization
- [ ] cleaning
- [ ] 20 minutes exercise
- [ ] 20 minutes language
- [ ] 20 minutes reading

### To-Do 
- [ ] Finish developing Chocoserver
- [ ] Start developing Chocoshop

### Plan
- want to finish my development in this week
- want to introduce team development

**Comment by taijusanagi** [comment]
### 20210422

### Tracking
- sleep: 22:00-5:00, 9:00-12:00
- weight: 64.1 kg
- fat: 20.9 %

### Routine
- [x] open journal
- [x] task organization
- [x] cleaning
- [ ] 20 minutes exercise
- [ ] 20 minutes language
- [ ] 20 minutes reading

### To-Do 
- [ ] Finish developing Chocoserver
- [ ] Start developing Chocoshop

### Plan
